#!/usr/bin/env python3
"""Build a synthetic river network for testing the SUMMA-mizuRoute coupling.

The bundled test domains have no river network, so there is nothing to route
through. This writes a topology file whose HRUs are the SUMMA GRUs of a given
attributes file, connected as a single chain of reaches: GRU i drains to reach
i, reach i drains to reach i+1, and the last reach is the outlet.

The network is synthetic and carries no hydrological meaning. It exercises the
coupling machinery -- runoff transfer, network construction, routing and output
-- and lets mass conservation be checked, but it cannot be compared against any
real-world reference.

Usage:
    make_test_topology.py <attributes.nc> <topology.nc>
"""

import sys

import numpy as np
from netCDF4 import Dataset

# nominal reach geometry; the values only need to be physically plausible
SEGMENT_LENGTH_M = 5000.0
SEGMENT_SLOPE = 0.001


def main(attribute_file, topology_file):
    with Dataset(attribute_file) as src:
        gru_id = np.array(src.variables["gruId"][:], dtype="i8")
        hru2gru = np.array(src.variables["hru2gruId"][:], dtype="i8")
        hru_area = np.array(src.variables["HRUarea"][:], dtype="f8")

    n = len(gru_id)
    # mizuRoute routes runoff per GRU, so a routing HRU is a SUMMA GRU here
    area = np.array([hru_area[hru2gru == g].sum() for g in gru_id])

    seg_id = np.arange(1, n + 1, dtype="i8")
    # a reach drains into the next one; downSegId <= 0 marks the outlet
    down_seg_id = np.concatenate([seg_id[1:], [0]]).astype("i8")

    with Dataset(topology_file, "w", format="NETCDF4") as dst:
        dst.createDimension("hru", n)
        dst.createDimension("seg", n)

        def put(name, dim, data, dtype, units, long_name):
            var = dst.createVariable(name, dtype, (dim,))
            var[:] = data
            var.units = units
            var.long_name = long_name

        put("hruId", "hru", gru_id, "i8", "-", "routing HRU id, matched to SUMMA GRU ids")
        put("area", "hru", area, "f8", "m2", "routing HRU area")
        put("hruToSegId", "hru", seg_id, "i8", "-", "id of the stream segment below each HRU")
        put("segId", "seg", seg_id, "i8", "-", "stream segment id")
        put("downSegId", "seg", down_seg_id, "i8", "-", "downstream segment id (<=0 at the outlet)")
        put("length", "seg", np.full(n, SEGMENT_LENGTH_M), "f8", "m", "segment length")
        put("slope", "seg", np.full(n, SEGMENT_SLOPE), "f8", "-", "segment slope")

        dst.description = (
            "synthetic single-chain river network generated by make_test_topology.py; "
            "for testing the SUMMA-mizuRoute coupling only"
        )
        dst.source_attributes = attribute_file

    print(f"wrote {topology_file}: {n} routing HRUs, {n} reaches, outlet at seg {seg_id[-1]}")
    print(f"total area: {area.sum():.4e} m2")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
