#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# SUMMA-mizuRoute coupling on the real Provo hydrofabric network
#
# test_mizuroute_bundled.sh proves the coupling machinery works, but on a
# synthetic single-chain network with no relation to any real domain. This
# script instead converts the actual Provo hydrofabric (the same network
# t-route routes through when this domain runs coupled inside ngen, see
# ../test_ngen/provo_run.sh) into a mizuRoute topology and routes the same
# SUMMA runoff through it.
#
# The point is not to get bit-for-bit agreement with t-route -- mizuRoute
# here uses the kinematic wave method (proven in test_mizuroute_bundled.sh)
# while t-route defaults to a Muskingum-Cunge-like scheme, and the SUMMA
# coupling interface does not currently pass hydraulic geometry (width,
# Manning's n) through to mizuRoute -- but it lets the two be compared on
# the same real network: same catchments, same reach lengths and slopes,
# same runoff. See compare_to_troute.py and the folder README.
#
# Requires a build configured with -DUSE_MIZUROUTE=ON, and python3 with netCDF4.
# ==============================================================================

# ------------------------------------------------------------------ settings --
SUMMA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SUMMA_EXE="$SUMMA_ROOT/bin/summa_sundials.exe"
DOMAIN="$SUMMA_ROOT/utils/test/test_ngen/domain_provo"
FILE_MANAGER="$DOMAIN/settings/SUMMA/fileManager.txt"

WORK_DIR="${1:-$TEST_DIR/provo_real_network}"
SUFFIX="provo_real_network"

# the bundled domain covers five years; two months is plenty to compare against
# a similarly short t-route run (a full 5-year t-route run is a much bigger ask)
SIM_END="2017-11-30 23:00"

echo
echo "======================================================================"
echo "SUMMA-mizuRoute coupling test (Provo domain, real hydrofabric network)"
echo "======================================================================"
echo "  executable:   $SUMMA_EXE"
echo "  file manager: $FILE_MANAGER"
echo "  work dir:     $WORK_DIR"
echo

for f in "$SUMMA_EXE" "$FILE_MANAGER"; do
  if [[ ! -f "$f" ]]; then echo "ERROR: not found: $f"; exit 1; fi
done

mkdir -p "$WORK_DIR/settings" "$WORK_DIR/output"

# ------------------------------------------------------- river network + config --
echo "Converting the real Provo hydrofabric to a mizuRoute topology..."
python3 "$TEST_DIR/hydrofabric_to_topology.py" \
        "$DOMAIN" \
        "$WORK_DIR/settings/topology.nc"

cp "$SUMMA_ROOT/external/mizuRoute/route/ancillary_data/param.nml.default" "$WORK_DIR/settings/"

cat > "$WORK_DIR/config.toml" <<EOF
# generated by test_mizuroute_provo_real_network.sh

[mizuRoute]

namelist_path = "$WORK_DIR/settings/"
namelist_file = "param.nml.default"

methods = "3"

dt = 3600

[hydrofabric]

hfabric_path = "$WORK_DIR/settings/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"
EOF

# the bundled file manager holds NextGen-relative paths, so rewrite them to absolute
# ones for this repository and redirect output into the work dir
sed -e "s|^settingsPath .*|settingsPath         '$DOMAIN/settings/SUMMA/'|" \
    -e "s|^forcingPath .*|forcingPath          '$DOMAIN/forcing/SUMMA_input/'|" \
    -e "s|^outputPath .*|outputPath           '$WORK_DIR/output/'|" \
    -e "s|^simEndTime .*|simEndTime           '$SIM_END'|" \
    "$FILE_MANAGER" > "$WORK_DIR/fileManager.txt"

# ----------------------------------------------------------------------- run --
echo
echo "Running coupled SUMMA-mizuRoute on the real network..."
"$SUMMA_EXE" -m "$WORK_DIR/fileManager.txt" -c "$WORK_DIR/config.toml" -s "$SUFFIX" \
             > "$WORK_DIR/run.log" 2>&1

if ! grep -q "finished simulation successfully" "$WORK_DIR/run.log"; then
  echo "ERROR: run did not complete; see $WORK_DIR/run.log"
  tail -20 "$WORK_DIR/run.log"
  exit 1
fi
echo "  run completed"

# -------------------------------------------------------------------- check --
OUTPUT=$(ls "$WORK_DIR/output/"*"${SUFFIX}"*timestep.nc | head -1)

echo
echo "Checking routed streamflow in $(basename "$OUTPUT")..."
python3 - "$OUTPUT" "$WORK_DIR/settings/topology.nc" <<'PYEOF'
import sys
import numpy as np
from netCDF4 import Dataset

output_file, topology_file = sys.argv[1], sys.argv[2]

with Dataset(output_file) as d:
    for name in ("Q_reach", "q_basin", "upArea", "seg"):
        if name not in d.variables:
            sys.exit(f"FAIL: {name} missing from the output file")
    Q = np.ma.filled(d.variables["Q_reach"][:].astype("f8"), np.nan)
    q_basin = np.ma.filled(d.variables["q_basin"][:].astype("f8"), np.nan)
    up_area = np.ma.filled(d.variables["upArea"][:].astype("f8"), np.nan)
    runoff = np.ma.filled(d.variables["averageRoutedRunoff"][:].astype("f8"), np.nan)
    seg = np.array(d.variables["seg"][:])

with Dataset(topology_file) as t:
    area = np.array(t.variables["area"][:], dtype="f8")
    down_seg = np.array(t.variables["downSegId"][:], dtype="i8")
    seg_id = np.array(t.variables["segId"][:], dtype="i8")

outlet_seg = int(seg_id[down_seg == 0][0])
outlet_index = int(np.where(seg == outlet_seg)[0][0])

fail = False

if np.nanmax(np.abs(q_basin - runoff)) != 0.0:
    print("FAIL: q_basin does not match SUMMA averageRoutedRunoff")
    fail = True
else:
    print("  runoff transfer:   exact")

outlet_up_area = up_area[outlet_index]
if not np.isclose(outlet_up_area, area.sum(), rtol=1e-6):
    print(f"FAIL: outlet upArea {outlet_up_area:.6e} != total area {area.sum():.6e}")
    fail = True
else:
    print(f"  drainage area:     outlet accumulates to {outlet_up_area:.4e} m2")

dt = 3600.0
vol_in = np.nansum(q_basin * area[None, :]) * dt
vol_out = np.nansum(Q[:, outlet_index, 0]) * dt
ratio = vol_out / vol_in
print(f"  inflow volume:     {vol_in:.4e} m3")
print(f"  outlet volume:     {vol_out:.4e} m3")
print(f"  out/in ratio:      {ratio:.4f}")
if not (0.90 <= ratio <= 1.0):
    print("FAIL: mass is not conserved through the network")
    fail = True
else:
    print("  mass balance:      conserved")

print(f"  outlet segId:      {outlet_seg} (wb-{outlet_seg} / cat-{outlet_seg} in the hydrofabric)")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
echo
echo "To compare against t-route: run ../test_ngen/provo_run.sh from the ngen"
echo "repo root over the same period, then run:"
echo "  python3 $TEST_DIR/compare_to_troute.py \\"
echo "      $OUTPUT \\"
echo "      <t-route stream output file/folder> \\"
echo "      $WORK_DIR/settings/topology.nc"
echo
