#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# SUMMA-mizuRoute coupling test on a bundled test domain
#
# test_mizuroute_coupling.sh compares a coupled run against a standalone
# mizuRoute run, which needs a real river network and a separate mizuRoute
# executable. This script instead runs the coupling end to end on a domain that
# ships with the repository, using a synthetic river network, and checks that
# water is conserved through the network.
#
# It verifies that runoff is transferred, the network is built, routing runs and
# output is written -- not that the routed flows match any real-world reference.
#
# Requires a build configured with -DUSE_MIZUROUTE=ON, and python3 with netCDF4.
# ==============================================================================

# ------------------------------------------------------------------ settings --
SUMMA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SUMMA_EXE="$SUMMA_ROOT/bin/summa_sundials.exe"
DOMAIN="$SUMMA_ROOT/test_ngen/domain_provo"
FILE_MANAGER="$DOMAIN/settings/SUMMA/fileManager.txt"

WORK_DIR="${1:-$SUMMA_ROOT/utils/regression/mizuroute_test}"
SUFFIX="mizuroute_test"

# the bundled domain covers five years; two months is plenty to exercise routing
SIM_END="2017-11-30 23:00"

echo
echo "======================================================================"
echo "SUMMA-mizuRoute coupling test (bundled domain, synthetic network)"
echo "======================================================================"
echo "  executable:   $SUMMA_EXE"
echo "  file manager: $FILE_MANAGER"
echo "  work dir:     $WORK_DIR"
echo

for f in "$SUMMA_EXE" "$FILE_MANAGER"; do
  if [[ ! -f "$f" ]]; then echo "ERROR: not found: $f"; exit 1; fi
done

mkdir -p "$WORK_DIR/settings" "$WORK_DIR/output"

# ------------------------------------------------------- river network + config --
echo "Building synthetic river network..."
python3 "$SUMMA_ROOT/utils/regression/make_test_topology.py" \
        "$DOMAIN/settings/SUMMA/attributes.nc" \
        "$WORK_DIR/settings/topology.nc"

cp "$SUMMA_ROOT/external/mizuRoute/route/ancillary_data/param.nml.default" "$WORK_DIR/settings/"

cat > "$WORK_DIR/config.toml" <<EOF
# generated by test_mizuroute_bundled.sh

[mizuRoute]

namelist_path = "$WORK_DIR/settings/"
namelist_file = "param.nml.default"

methods = "3"

dt = 3600

[hydrofabric]

hfabric_path = "$WORK_DIR/settings/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"
EOF

# the bundled file manager holds NextGen-relative paths, so rewrite them to absolute
# ones for this repository and redirect output into the work dir
sed -e "s|^settingsPath .*|settingsPath         '$DOMAIN/settings/SUMMA/'|" \
    -e "s|^forcingPath .*|forcingPath          '$DOMAIN/forcing/SUMMA_input/'|" \
    -e "s|^outputPath .*|outputPath           '$WORK_DIR/output/'|" \
    -e "s|^simEndTime .*|simEndTime           '$SIM_END'|" \
    "$FILE_MANAGER" > "$WORK_DIR/fileManager.txt"

# ----------------------------------------------------------------------- run --
echo
echo "Running coupled SUMMA-mizuRoute..."
"$SUMMA_EXE" -m "$WORK_DIR/fileManager.txt" -c "$WORK_DIR/config.toml" -s "$SUFFIX" \
             > "$WORK_DIR/run.log" 2>&1

if ! grep -q "finished simulation successfully" "$WORK_DIR/run.log"; then
  echo "ERROR: run did not complete; see $WORK_DIR/run.log"
  tail -20 "$WORK_DIR/run.log"
  exit 1
fi
echo "  run completed"

# -------------------------------------------------------------------- check --
OUTPUT=$(ls "$WORK_DIR/output/"*"${SUFFIX}"*timestep.nc | head -1)

echo
echo "Checking routed streamflow in $(basename "$OUTPUT")..."
python3 - "$OUTPUT" "$WORK_DIR/settings/topology.nc" <<'PYEOF'
import sys
import numpy as np
from netCDF4 import Dataset

output_file, topology_file = sys.argv[1], sys.argv[2]

with Dataset(output_file) as d:
    for name in ("Q_reach", "q_basin", "upArea", "seg"):
        if name not in d.variables:
            sys.exit(f"FAIL: {name} missing from the output file")
    Q = np.ma.filled(d.variables["Q_reach"][:].astype("f8"), np.nan)
    q_basin = np.ma.filled(d.variables["q_basin"][:].astype("f8"), np.nan)
    up_area = np.ma.filled(d.variables["upArea"][:].astype("f8"), np.nan)
    runoff = np.ma.filled(d.variables["averageRoutedRunoff"][:].astype("f8"), np.nan)

with Dataset(topology_file) as t:
    area = np.array(t.variables["area"][:], dtype="f8")

fail = False

# the runoff mizuRoute receives must be exactly what SUMMA produced
if np.nanmax(np.abs(q_basin - runoff)) != 0.0:
    print("FAIL: q_basin does not match SUMMA averageRoutedRunoff")
    fail = True
else:
    print("  runoff transfer:   exact")

# drainage area must accumulate down the chain, ending at the domain total
if not np.all(np.diff(up_area) > 0):
    print("FAIL: upArea does not increase down the chain")
    fail = True
elif not np.isclose(up_area[-1], area.sum(), rtol=1e-9):
    print(f"FAIL: outlet upArea {up_area[-1]:.6e} != total area {area.sum():.6e}")
    fail = True
else:
    print(f"  drainage area:     accumulates to {up_area[-1]:.4e} m2")

# water in must equal water out, less whatever is still in channel storage
dt = 3600.0
vol_in = np.nansum(q_basin * area[None, :]) * dt   # m s-1 * m2 * s
vol_out = np.nansum(Q[:, -1, 0]) * dt              # m3 s-1 * s
ratio = vol_out / vol_in
print(f"  inflow volume:     {vol_in:.4e} m3")
print(f"  outlet volume:     {vol_out:.4e} m3")
print(f"  out/in ratio:      {ratio:.4f}")
if not (0.95 <= ratio <= 1.0):
    print("FAIL: mass is not conserved through the network")
    print("      (a ratio just below 1 is expected: water left in channel storage)")
    fail = True
else:
    print("  mass balance:      conserved")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
echo
