#!/usr/bin/env bash

set -e

export CC=/usr/bin/gcc-6
export FC=/usr/bin/gfortran-6

if [ -z "$WORKDIR" ]; then
    export WORKDIR=$HOME/workdir
    mkdir -p $WORKDIR
fi

if [ -z "$INSTALLDIR" ]; then
    export INSTALLDIR=$HOME/installdir
    mkdir -p $INSTALLDIR
fi

function install_szip {
    echo install_szip
    cd $WORKDIR
    wget --no-check-certificate -q http://www.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz
    tar -xzf szip-2.1.1.tar.gz
    cd szip-2.1.1
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export CPPFLAGS="$CPPFLAGS -I${INSTALLDIR}/include"
    export LDFLAGS="$LDFLAGS -L${INSTALLDIR}/lib"
}

function install_hdf5 {
    echo install_hdf5
    cd $WORKDIR
    wget --no-check-certificate -q https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.gz
    tar -xzf hdf5-1.10.5.tar.gz
    cd hdf5-1.10.5
    ./configure --prefix=$INSTALLDIR &> config.log
    make
    make install
    export LIBDIR=${INSTALLDIR}/lib
}

function install_netcdf_c {
    echo install_netcdf_c
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-c-4.7.3.tar.gz
    tar -xzf netcdf-c-4.7.3.tar.gz
    cd netcdf-c-4.7.3
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
    export LD_LIBRARY_PATH=${INSTALLDIR}/lib
}

function install_netcdf_fortran {
    echo install_netcdf_fortran
    cd $WORKDIR
    wget --no-check-certificate -q ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.5.2.tar.gz
    tar -xzf netcdf-fortran-4.5.2.tar.gz
    cd netcdf-fortran-4.5.2
    ./configure --prefix=$INSTALLDIR &> config.log
    make &> make.log
    make install
}

function summa_before_install {
    echo summa_before_install
    # Install szip (used by hdf5)
    install_szip
    # Install HDF5
    install_hdf5
    # Install NetCDF-C
    install_netcdf_c
    # Install NetCDF fortran
    install_netcdf_fortran
}

function summa_install {
    echo summa_install
    cd ${TRAVIS_BUILD_DIR}
    export F_MASTER=${TRAVIS_BUILD_DIR}
    export FC=gfortran
    export FC_EXE=gfortran-6
    export INCLUDES='-I${INSTALLDIR}/include -I/usr/include'
    export LIBRARIES='-L${INSTALLDIR}/lib -lnetcdff -L/usr/lib -llapack -lblas'
    make -C build/ -f Makefile &> make.log
}

function summa_script {
    echo summa_script
    ${TRAVIS_BUILD_DIR}/bin/summa.exe
}

function summa_after_success {
  echo summa_after_success
  echo "SUMMA build succeeded"
}

function summa_after_failure {
  echo summa_after_failure
  echo "SUMMA build failed"
}
